export const ADD_INGREDIENT = ' ADD_INGREDIENT';
export const REMOVE_INGREDIENT = ' REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const INNIT_INGREDIENTS = 'INNIT_INGREDIENTS';
export const FETCH_INGREDIENT_FAILED = 'FETCH_INGREDIENT_FAILED';
export const INGREDIENT_FAIL_RESET = 'INGREDIENT_FAIL_RESET';
export const START_INGREDIENT_FETCH = 'START_INGREDIENT_FETCH';

export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILED = 'SIGN_IN_FAILED';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILED = 'FORGOT_PASSWORD_FAILED ';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILED = 'RESET_PASSWORD_FAILED';
export const LOGOUT = 'LOGOUT';
export const SWITCH_ERROR_FALSE = 'SWITCH_ERROR_FALSE';
export const WAIT_REPONSE = 'WAIT_REPONSE';

export const GET_CONTACT_DETAILS = 'GET_CONTACT_DETAILS';
export const SEND_FULL_ORDER = 'SEND_FULL_ORDER';
export const START_ORDER_SEND = 'START_ORDER_SEND';
export const SEND_ORDER_SUCCESS = 'SEND_ORDER_SUCCESS';
export const SEND_ORDER_FAIL = 'SEND_ORDER_FAIL';
export const ORDER_RESET = 'ORDER_RESET';
export const FETCH_ORDERS = 'FETCH_ORDERS';
